
services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy &&
             node src/index.js"

volumes:
  postgres_data:
